<?php

namespace AppBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    /**
    * Méthode qui retourne la liste des clients par ordre asc
    *
    * @return Client[] 
    */
    public function filtreParNom(): array
    {
        return $this->createQueryBuilder('c')
            ->addOrderBy('c.nom', 'ASC')
            ->getQuery()
            ->getResult()
        ;
    }
}
