<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

    /**
    * Méthode qui retourne la liste des produits par ordre desc
    *
    * @return Produit[]
    */
    public function produitDesc(): array
    {
        return $this->createQueryBuilder('p')
            ->addOrderBy('p.prix', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }

    /**
    * Méthode qui retourne la liste des produits par ordre asc
    *
    * @return Produit[] 
    */
    public function produitAsc(): array
    {
        return $this->createQueryBuilder('p')
            ->addOrderBy('p.prix', 'ASC')
            ->getQuery()
            ->getResult()
        ;
    }
}
